### ISSUE TITLE
Analysis tool

### ISSUE THREAD

**Issue by BenjiG59** [andre0707/wIgHelper#1]
I just tried the WIG analysis tool on two and nothing happened. GC531HP and GC6M581

**Comment by andre0707** [comment]
> 

Hi there!
They both work fine on my device. 
you download the related cartridge and open  it with wIgHelper. Then it should appear on the “Cartridges” tab. There you select it to get to the detail view and then use the wrench button on the top right to analyse it. 
depending on the size of the cartridge and your iOS device this takes a couple of seconds. But there is a progress message displayed on the middle of the screen. When analysis is done, the view should refresh and you can see all the analysis results.



if you had the pro version of the app in the past, 1 full analysis is included. Else or for more you need the cartridge analysis in app purchase. You can get it in the “settings” tab.

**Comment by BenjiG59** [comment]
Thanks for the reply. Just tried again. The dialogue box shows up for a split second and then disappears. Nothing else happens. I deleted the app and tried again. Same thing. How do you load the cartridges? I'm going to the website, download and then choose to open with the app. Is there another way I should be loading them?

Benji Goodrich
***@***.***
303.704.6670

**Comment by andre0707** [comment]
I open the wherigo.com website in safari, download the cartridge and then click open with wIgHelper.
If it is visible in the cartridges list view inside wIgHelper, the download and copying to the app should have worked.
Which device and iOS version do you use? I assume there is also enough disk space available?

Would you mind sharing a short screen recording (https://support.apple.com/guide/iphone/take-a-screenshot-or-screen-recording-iphc872c0115/ios ) starting right before clicking the wrench button?
Not sure if uploading videos here work. Here's also my email address: feedback@aaindustries.de

**Comment by BenjiG59** [comment]
Same steps for me except using Chrome. Using iPhone 11 with ios 15.2. Plenty of space. Download works fine. I see the cartridge loaded just fine. I tried with a few other cartridges and the same result.

Benji Goodrich
***@***.***
303.704.6670

**Comment by BenjiG59** [comment]
I can do a screen video capture if that's helpful.

Benji Goodrich
***@***.***
303.704.6670

**Comment by andre0707** [comment]
That is very strange. I tested with multiple devices and it worked fine on all so far. 
I'm currently adding some error codes for every step which potentially could fail and will update the app in the next minutes. 
I hope apple will release the app updated soon and I would then like to ask you for the error code you get then.

**Comment by BenjiG59** [comment]
Absolutely! Happy to help in any way I can. I'm a beta tester for Cachly so I don't mind a few things not quite working right.

Benji Goodrich
***@***.***
303.704.6670

**Comment by andre0707** [comment]
Would you mind switching over to TestFlight then? This would probably speed it up a little, so I can add the needed changes based on the error code you will get. 
https://testflight.apple.com/join/ZBPIF2mg

**Comment by andre0707** [comment]
Just submitted version 3.1 which will display error codes.

**Comment by BenjiG59** [comment]
Great. I'll let you know what happens when I use that version.

Benji Goodrich
***@***.***
303.704.6670

**Comment by BenjiG59** [comment]
Just messed around some more. If I download in Safari and import it works. But not from Chrome.

Benji Goodrich
***@***.***
303.704.6670

**Comment by andre0707** [comment]
Interesting!

I also downloaded it with Chrome browser, after you mentioned it and it looks like the file downloaded with Chrome is way smaller than the actual cartridge should be. For the "travel the solar system" it shows me it wants to download 928KB, but the downloaded file is just 65KB.
I also can not open the cartridge downloaded with Chrome with the official Wherigo app to play it. 

I will add an error message which will mention to try downloading it with Safari. 
I am sorry for the inconvenience. I hope everything else works as expected though.

Thank you for reporting the problem

**Comment by BenjiG59** [comment]
I've been looking at a bunch of WIGs now that I know how to properly download. This tool is incredible!! I had only used to solve reverse WIGs before but this solver tool is awesome. I will still go through the experience for many, but obviously so many don't work right. So this is awesome. We'll worth the additional purchase. Thanks!

--
Benji Goodrich
***@***.***

**Comment by andre0707** [comment]
Thank you! I appreciate the feedback :)

Just submitted version 3.1 to the AppStore which will include better error messages, some UI improvements and a new analysis category for 'inputs'. This should make it easier to get the right answer when stuck while playing a cartridge.
