### ISSUE TITLE
Import cartridge 

### ISSUE THREAD

**Issue by BenjiG59** [andre0707/wIgHelper#3]
I can't remember and can't seem to figure out how to import cartridges. Thanks.

**Comment by andre0707** [comment]
Hi there,

you just open the cartridge file (.gwc) with wIgHelper. 
If the file is saved in your “Files” app just click and hold it to get the context menu. Then pick “Share” and chose the wIgHelper app.
(Caution: If you only click it, it will probably just open with Wherigo app; so make sure to hold long enough to get the menu)


In files app, you can also navigate to the regular Wherigo App folder to see all the wherigos you saved in this app. From there you can also share it with wIgHelper by clicking and holding.


If you receive the cartridge file via AirDrop, you should get asked in which app you want to open it. 

If you receive the cartridge via email you can also click and hold to get the context menu. Pick the share option to share it with wIgHelper.



Please let me know if this helped

**Comment by BenjiG59** [comment]
Thanks! This is helpful. However, I can't get the cartridges from the WIG app to go to the Helper app. No share option. I'll suggest that to Nic the developer. I'm a Cachly beta tester and have direct contact with him.

**Comment by andre0707** [comment]
Not directly from the Wherigo app. 
If you open the “Files” app, section “On my device” then there is a folder “Wherigo” which holds all the cartridges.
Long click one of them will present the context menu including an option for the share sheet

**Comment by BenjiG59** [comment]
Oh! I didn't know that was there. Doesn't spell out the names of all the cartridges I have loaded. But good to know that's an option. I've posed the "share" question to Nic. Because it was developed for HQ, they'd have to authorize a generic share feature. We'll see.

**Comment by andre0707** [comment]
I think the cryptic naming happens when the cartridge is downloaded inside the Wherigo App. 
The naming is fine on my device when I download the cartridges directly in Safari browser.

Anyways, I think the original question is answered, so I will close this issue.
