### ISSUE TITLE
Cartridge analysis partial fail

### ISSUE THREAD

**Issue by jamesanderson16** [andre0707/wIgHelper#4]
Some cartridges will analyse but won't give the full details of the cartridge (e.g. start and/or end coordinates are N 00° 00.000' E 000° 00.000' even though the cache is in South Australia)

**Comment by andre0707** [comment]
Can you please provide the GC code or the link to the cartridge where this is the case?

**Comment by jamesanderson16** [comment]
Any of the caches similar to this and others 

GC8RKRQ

There are multiple in South Australia

**Comment by andre0707** [comment]
GC8RKRQ worked totally fine on my iPhone. 
Can you please mention the steps you did? 

There were problems in the past when third party browsers were used to download the Cartridge. Did you use Safari to download the cartridge?

**Comment by andre0707** [comment]
I found a problem with the cartridge GC9JX6Z. This should be related.
I uploaded an app update to the AppStore. Should be available soon.

Thanks for reporting the problem and sorry for the inconvenience.

**Comment by jamesanderson16** [comment]
Thanks,

I'll let you know if this is fixed  when I can download the update 😊😉

**Comment by jamesanderson16** [comment]
It's fixed from what I see

I'll let you know if there are any others that don't work

Thanks 

James0116

**Comment by andre0707** [comment]
Great.
I’ll close this ticket for now then.
