### ISSUE TITLE
New Reverse Wherigo cartridge

### ISSUE THREAD

**Issue by jamesanderson16** [andre0707/wIgHelper#5]
Just a heads up there is a new Reverse Wherigo Cartridge made by an Australian geocacher

Here is the link to the cartridge 

https://www.wherigo.com/cartridge/details.aspx?CGUID=01ea16ae-a18a-463b-801b-bd8e4434bb7f

Thanks 

James0116

**Comment by andre0707** [comment]
I added a "source" button in the Reverse Cache tab of the app to chose between the original -Waldmeister- reverse wherigo and this new one. 
App Update will be available soon

**Comment by jamesanderson16** [comment]
Not urgent, but you might want the description to change when changing over the reverse solver types (see picture)![image](https://user-images.githubusercontent.com/55370705/193246247-15655ba6-9754-4ef8-86cb-31be1aa3157d.png)

**Comment by andre0707** [comment]
Thanks! I missed this. Description will be changed with the next update. I also just spotted a missing translation. 
I will close this ticket here though, since I think the new reverse solver itself works.
