### ISSUE TITLE
Request to be able to copy 'Items' text

### ISSUE THREAD

**Issue by jamesanderson16** [andre0707/wIgHelper#6]
Hi,

Some cartridges have the coordinates in the items so it would be handy to be able to copy the text of the items sometimes

Thanks

James A

**Comment by andre0707** [comment]
I agree, this is a helpful addition. 
Just added it and submitted an update to the AppStore. Should be available soon.


I would appreciate an [AppStore review](https://itunes.apple.com/us/app/wighelper/id1260686079?action=write-review) if you find the app helpful :)

**Comment by jamesanderson16** [comment]
Jeese that was quick (In the sence Apple has approved it already)

Thanks for your help,

I don't usually do Apple Store reviews but I do do star ratings so I will do it now

**Comment by andre0707** [comment]
Thank you, ratings also help a lot.
I will close this item now.
