### ISSUE TITLE
Wherigo Cartridge failed to properly analyse some cartridge's

### ISSUE THREAD

**Issue by jamesanderson16** [andre0707/wIgHelper#7]
Please see this Gc code to see cartridge as it doesn't provide all details link in the notes

https://coord.info/GC7J3AM

Thanks

James0116

**Comment by andre0707** [comment]
The cartridge analysis worked without errors on my device.
Looking at the provided cartridge source code from the analysis, I also don’t see a missing category in the analysis result.
The data in the categories I would expect to see seems complete.

There are no waypoints specified in the source code, so the app can not show any.
However, the owner tried to hide the final coordinates somewhat. 
If you check the source code you will find the section:

Text = ("The final co-ordinates for the geocache are…<BR>S37 46." ..
_jwh * 10 - 252) ..
"<BR>E 144
58.0") .. _jwh - 42


I looked for the variable _jwh in the source code and found the initialization as _jwh=100
I didn’t check if that was the only occurrence or if it changed at some later point. 
 
So no guarantee the final is at S 37 46.748 E 144 58.058, but that’s what it looks to me like taking a very short look at the source code.
To be sure, you can check the whole source code for changes of _jwh.

After all, all the information are in the source code. Some owner just try to make it harder to directly see coordinates.


Please let me know if the analysis did not work on your device or specify a little more detailed, what’s not working as expected.

**Comment by andre0707** [comment]
No further feedback, so I will close this issue.
